spring:
  datasource:
    url: jdbc:mysql://124.223.161.244:3306/user_center
    username: nicefang
    password: 531184
    driver-class-name: com.mysql.cj.jdbc.Driver
  #session失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
